# Generated by Django 5.0.6 on 2024-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistory',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
